const actionTypes = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  EDIT_CHANGE: 'EDIT_CHANGE',
  EDIT_SUBMIT: 'EDIT_SUBMIT',
  CHECK_ITEM_DONE: 'CHECK_ITEM_DONE',
  CLEAR_COMPLETE: 'CLEAR_COMPLETE',
  SET_FILTER: 'SET_FILTER',
};

export default actionTypes;